name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install html-validator
        run: npm install -g html-validator-cli
      
      - name: Validate HTML
        run: |
          echo "Checking HTML files..."
          for file in $(find . -name "*.html"); do
            if ! grep -q "<!DOCTYPE html>" "$file"; then
              echo "Error: No DOCTYPE found in $file"
              exit 1
            fi
          done
      
      - name: Check for required files
        run: |
          required_files=(
            "index.html"
            "css/styles.css"
            "js/app.js"
            "js/components/BookingComponent.js"
            "js/components/FeedbackComponent.js"
            "js/components/LoginModal.js"
            "js/components/MembershipComponent.js"
          )
          
          for file in "${required_files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "Error: Required file $file is missing"
              exit 1
            fi
          done
      
      - name: Validate JavaScript files
        run: |
          echo "Checking JavaScript files..."
          for file in $(find . -name "*.js"); do
            echo "Checking $file"
            node --check "$file" || exit 1
          done