# .github/workflows/portfolio-trigger.yml
name: Trigger Portfolio Update

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:  # Allow manual triggering

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Validate secret exists
        run: |
          if [ -z "${{ secrets.PAT_TOKEN }}" ]; then
            echo "❌ Error: PAT_TOKEN secret is not configured"
            echo "Please add a Personal Access Token as a secret named PAT_TOKEN"
            exit 1
          else
            echo "✅ PAT_TOKEN secret is configured"
          fi
          
      - name: Trigger portfolio update
        id: trigger
        run: |
          echo "🚀 Triggering portfolio update..."
          
          response=$(curl -s -w "\n%{http_code}" -X POST \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/isaacbrendel/isaacbrendel.github.io/dispatches \
            -d '{"event_type": "repo_updated", "client_payload": {"repository": "2MittensFarm", "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"}}')
          
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')
          
          echo "HTTP Status Code: $http_code"
          
          if [ "$http_code" -eq 204 ]; then
            echo "✅ Successfully triggered portfolio update"
          elif [ "$http_code" -eq 404 ]; then
            echo "❌ Error: Repository not found or PAT doesn't have access"
            echo "Please check:"
            echo "  1. The repository exists: isaacbrendel/isaacbrendel.github.io"
            echo "  2. Your PAT has 'repo' scope"
            echo "Response: $body"
            exit 1
          elif [ "$http_code" -eq 401 ]; then
            echo "❌ Error: Invalid or expired PAT_TOKEN"
            echo "Please check your Personal Access Token"
            exit 1
          else
            echo "❌ Error: Unexpected response"
            echo "HTTP Code: $http_code"
            echo "Response: $body"
            exit 1
          fi
          
      - name: Log trigger details
        if: success()
        run: |
          echo "📝 Trigger Details:"
          echo "  - Repository: 2MittensFarm"
          echo "  - Target: isaacbrendel.github.io"
          echo "  - Triggered by: ${{ github.actor }}"
          echo "  - Commit: ${{ github.sha }}"
          echo "  - Timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
